#### Answer_1

In [5]:
import numpy as np

list_ = [ '1' , '2' , '3' ,'4' , '5' ]

array_list = np.array(object = list_)

In [7]:
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

#### Answer_2

In [ ]:
import numpy as np

list_ = [ '1' , '2' , '3' ,'4' , '5' ]

array_list = np.array(object = list_)

In [12]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### Answer_3

In [14]:
import numpy as np

list_ = [ '1' , '2' , '3' ,'4' , '5' ]

array_list = np.array(object = list_)

In [15]:
array_list = np.array(object = list_, dtype = int)


In [16]:
type(list_)

list

In [17]:
type(array_list)

numpy.ndarray

In [18]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [19]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


#### Answer_4

In [20]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [21]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
num_array.shape

(2, 3)

In [24]:
num_array.size

6

#### Answer_5

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Answer_6

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])